// examples/base/vue/App.vue
<template>
      <div id="app-vue">
        <p>{{census.count}}</p>
        <button class="plus" @click="census.plus">plus</button>
        <button class="minus" @click="census.minus">minus</button>
        <input class="input" type="number" :value="census.count" @input="(e) => census.setCount(parseInt(e.target.value) || 0)" />
      </div>
</template>
<script>
  export default {
    computed: {
      census () {
        return this.$vut.getModule('census')
      }
    }
  }
</script>

// examples/base/react/App.jsx
import React from 'react'
import { connect } from 'vut-react'

class App extends React.Component {
  render () {
    const { census } = this.props
    return (
      <div>
        <p>{census.count}</p>
        <button onClick={() => census.plus()}>plus</button>
        <button onClick={() => census.minus()}>minus</button>
        <input type="number" value={census.count} onInput={(e) => census.setCount(parseInt(e.target.value) || 0)} />
      </div>
    )
  }
}

export default connect(App, (vut) => {
  return vut.getModule({ census: 'census' })
})
